language: csharp
solution: WindowsFormsTest.sln
script:
  - xbuild /p:Configuration=Release WindowsFormsTest.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./UnitTest/bin/Release/UnitTest.dll