language: csharp
solution: WindowsFormsTest.sln
install:
  - nuget restore WindowsFormsTest.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release WindowsFormsTest.sln
  - mono ./testrunner/NUnit.Runners.3.7.0/tools/nunit-console.exe ./UnitTest/bin/Release/UnitTest.dll