language: csharp
solution: WindowsFormsTest.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore WindowsFormsTest.sln
after_script:
  - nunit-console UnitTest/bin/Release/UnitTest.dll