language: csharp
sudo: enabled
solution: WindowsFormsTest.sln
install:
  - sudo apt-get install nunit-console
  - nuget restore WindowsFormsTest.sln
script:
  - xbuild /p:Configuration=Release WindowsFormsTest.sln